export default {
    'hammer' : {
         0 : 'Splintered Club',
         1 : 'Wooden Mallet',
         2 : 'Primal Mace',
         3 : 'Orcish Bludgeon',
         4 : 'Heavy Mace',
         5 : 'Iron Basher',
         6 : 'Darkmetal Maul',
         7 : 'Divine Gavel',
         8 : 'Hallowed Hammer',
         9 : 'Dwarven Maul',
        10 : 'Coldforged Gavel',
        11 : 'Skullshatterer',
        12 : 'Amboss',
        13 : 'Benevolence',
        14 : 'Hammer of Gaia',
        15 : 'Worldender',
        16 : 'Nightmare'
    },
    'bow' : {
         0 : 'Driftwood Shortbow',
         1 : 'Novice Shortbow',
         2 : 'Curved Shortbow',
         3 : 'Adventurer\'s Shortbow',
         4 : 'Longbow',
         5 : 'Bone Bow',
         6 : 'Elven Bow',
         7 : 'Ancient Bow',
         8 : 'Iron Piercer',
         9 : 'Silver Recurve',
        10 : 'Assassin\'s Bow',
        11 : 'Hellfire Warbow',
        12 : 'Skyfire Warbow',
        13 : 'Widowmaker',
        14 : 'Stormsong',
        15 : 'Scarebow',
        16 : 'Fury'
    },
    'staff': {
         0 : 'Broken Twig',
         1 : 'Cracked Stick',
         2 : 'Gnarled Broomstick',
         3 : 'Oak Staff',
         4 : 'Mystic Wand',
         5 : 'Bone Staff',
         6 : 'Encrusted Rod',
         7 : 'Imbued Staff',
         8 : 'Emerald Staff',
         9 : 'Sapphire Staff',
        10 : 'Frozen Greatstaff',
        11 : 'Infernal Staff',
        12 : 'Hellfire Greatstaff',
        13 : 'Divine Staff',
        14 : 'Crystal Core',
        15 : 'Witch\'s Heart',
        16 : 'Deathweaver'
    },
    'sword': {
         0 : 'Wooden Sword',
         1 : 'Rusty Ironsword',
         2 : 'Troll Blade',
         3 : 'Broadsword',
         4 : 'Longsword',
         5 : 'Gladius',
         6 : 'Greatsword',
         7 : 'Templar Greatsword',
         8 : 'Ghastly Scimitar',
         9 : 'Nullfire Sword',
        10 : 'King\'s Rapier',
        11 : 'Void Blade',
        12 : 'Zerstörer',
        13 : 'Hearteater',
        14 : 'Demonedge',
        15 : 'Excalibur',
        16 : 'Harbinger'
    },
    'armlet': {
         0 : 'Simple Wristbands',
         1 : 'Makeshift Armbands',
         2 : 'Leather Armlets',
         3 : 'Bone Bracelets',
         4 : 'Iron Vambraces',
         5 : 'Imbued Bracers',
         6 : 'Ember Cuffs',
         7 : 'Mirror Armlets',
         8 : 'Golem Fragments',
         9 : 'Coldforged Bracers',
        10 : 'Blackstars',
        11 : 'Mobiuses',
        12 : 'Guardians'
    },
    'armor': {
         0 : 'Potato Sack',
         1 : 'Faded Garment',
         2 : 'Adventurer\'s Tunic',
         3 : 'Leather Jerkin',
         4 : 'Scaled Chestguard',
         5 : 'Sky Mail',
         6 : 'Shadow Cloak',
         7 : 'Runic Halfplate',
         8 : 'Hellfire Fullplate',
         9 : 'Soulkeeper',
        10 : 'Deathless'
    },
    'bag': {
         0 : 'Linen Pouch',
         1 : 'Adventurer\'s Rucksack',
         2 : 'Purpur Duffel',
         3 : 'Elven Saddlebag',
         4 : 'Moss Enigma'
    },
    'boot': {
         0 : 'Sandals',
         1 : 'Cloth Footpads',
         2 : 'Leather Shoes',
         3 : 'Bone Brogans',
         4 : 'Scaled Treads',
         5 : 'Shadow Shoes',
         6 : 'Wartorn Boots',
         7 : 'Imbued Treads',
         8 : 'Skyswift Boots',
         9 : 'Coldforged Greaves',
        10 : 'Cloudrunners',
        11 : 'Talaria',
        12 : 'Starshards'
    },
    'glove': {
         0 : 'Hand Wraps',
         1 : 'Cloth Mitts',
         2 : 'Leather Gloves',
         3 : 'Bone Grips',
         4 : 'Iron Gauntlets',
         5 : 'Imbued Battlefists',
         6 : 'Wartorn Mitts',
         7 : 'Fiery Handguards',
         8 : 'Empowerment Gloves',
         9 : 'Coldforged Fists',
        10 : 'Eternals',
        11 : 'Phrygians',
        12 : 'Titans'
    },
    'ring': {
         0 : 'Woven Band',
         1 : 'Ironbark Loop',
         2 : 'Brass Unity',
         3 : 'Hollowed Bone',
         4 : 'Elven Heirloom',
         5 : 'Imbued Union',
         6 : 'Arcane Ring',
         7 : 'Emerald Band',
         8 : 'Infernal Ring',
         9 : 'Ancient Signet',
        10 : 'Reverence',
        11 : 'Gyges'
    },
    'amulet': {
         0 : 'Rotten Talisman',
         1 : 'Wolf\'s Collar',
         2 : 'Bone Necklace',
         3 : 'Werewolf\'s Claw',
         4 : 'Eagle\'s Talon',
         5 : 'Shadow Scarab',
         6 : 'Mystic Shard',
         7 : 'Omega Medallion',
         8 : 'Verstärker',
         9 : 'Tempest Carcanet',
        10 : 'Ankh',
        11 : 'Yggdrasil Pendant'
    },
    'quiver': {
         0 : 'Linen Quiver',
         1 : 'Rustic Quiver',
         2 : 'Snakeskin Quiver',
         3 : 'Reinforced Exemplar',
         4 : 'Lazarus\'s Revenge',
         5 : 'Dragonhide Cynosure',
         6 : 'Lotharien',
         7 : 'Treant\'s Gift',
         8 : 'Vodhrai',
         9 : 'Pompeii'
    },
    'shield': {
         0 : 'Wooden Shield',
         1 : 'Buckler',
         2 : 'Old Bulwark',
         3 : 'Metal Guard',
         4 : 'Darkmetal Shield',
         5 : 'Spiked Warshield',
         6 : 'Protecteron',
         7 : 'Svalinn',
         8 : 'Ancile',
         9 : 'Aegis'
    },
    'totem': {
         0 : 'Dream Feathers',
         1 : 'Voodoo Doll',
         2 : 'Glowing Chicken',
         3 : 'Divine Beads',
         4 : 'Templar\'s Resolve',
         5 : 'Holy Cricket',
         6 : 'Laughing Skulls',
         7 : 'Hive Mind',
         8 : 'Nganga\'s Serpent',
         9 : 'Sangoma\'s Bones'
    },
    'orb': {
         0 : 'Rat Skull',
         1 : 'Crystal Globe',
         2 : 'Seer\'s Stone',
         3 : 'Philosopher\'s Stone',
         4 : 'Cyclops\'s Eye',
         5 : 'Nüwa\'s Rondure',
         6 : 'Baetylus\'s Eye',
         7 : 'Benben Stone',
         8 : 'Silthrim',
         9 : 'Lich\'s Phylactery'
    }
}
